### ISSUE TITLE
Should we deprecate this repo?

### ISSUE THREAD

**Issue by gruyaume** [omec-project/pfcp#58]
## Description

I'm opening this issue to entertain the possibility of deprecating this repository. There is already a well maintained GO PFCP library out there, [wmnsk/go-pfcp](https://github.com/wmnsk/go-pfcp), and the SMF could handle PFCP communication using it instead of `omec-project/pfcp`. Here I want to discuss whether or not this is a good idea.

### Ease of life for developers

We are currently using two different projects for PFCP communication between the SMF and the UPF making it harder to understand and contribute changes involving PFCP communication. The UPF uses `wmnsk/go-pfcp` and the SMF uses `omec-project/pfcp`, both with the same purpose. Why not depend on the 1 project for PFCP communication instead of 2.

### Security and reliability

`go-pfcp` is well maintained, tracks changes to 3GPP releases, has 53 dependents (making it more likely to receive bug fixes and security patches), and has only 1 dependency ([go-cmp](https://github.com/google/go-cmp)).

### Maintainability

Archiving this repository would reduce by 1 the total number of repositories maintained for Aether, making the project easier to support with a limited amount of developers.

## Effort

This activity would need to be done in three phases:
1. Replace PFCP message management with `wmnsk/go-pfcp` in the SMF
2. Bring `omec-project/pfcp` to maintenance mode where only security patches would be done if required
3. Archive `omec-project/pfcp` after X amount of time

**Comment by gab-arrobo** [comment]
Short answer is `yes`
Long answer: This is something that we had discussed in the last 2-3 TST meetings and it is part of the roadmap. However, for the implementation, we are going to start with the SBI for the 3GPP release upgrade and after that we will move to work on the N4 interface (PFCP)

**Comment by gruyaume** [comment]
I would have to align with the team, but yes, this should be an effort we can help with.

**Comment by thakurajayL** [comment]
We are already using this in UPF and we wish to move SMF also to this go-pfcp module. ITs on roadmap and we are happy if you could contribute to this. Thanks
